#!/usr/bin/env bash
# adding secure connection to web server

display_info() {
    subdomain=$1
    domain=$2

    res=$(dig "$1.$2" | grep -A 1 "ANSWER SECTION" | tail -n 1)
    echo "$res" | awk -v subdomain="$subdomain" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
    }

main() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            display_info "$sub" "$domain"
        done
    else
        display_info "$subdomain" "$domain"
    fi
}

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

main "$@"
