#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80 When querying
# As an answer file, write a Bash script that configures
# You cant use systemctl for restarting nginx

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s/listen 80;/listen 80;/g" /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
