#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80 When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
#As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
#You can’t use systemctl for restarting nginx

if [ "$#" -ne 0 ]; then
    echo "Usage: 0-install_nginx_web_server"
    exit 1
fi

sudo apt update
sudo apt install -y nginx
sudo sed -i 's/80 default_server/80 default_server default/g' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start
