#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.


sudo apt-get update -y
sudo apt-get install -y nginx

sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    root /var/www/html;
    index index.html index.htm;
}" > /etc/nginx/sites-available/default

sudo service nginx restart
