#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains

sudo apt-get update -y
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World' | sudo tee /var/www/html/index.html

new_confg=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;

    location /404.html {
        internal;
    }

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}"


echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo "$new_confg" | sudo tee /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ];
then
    sudo service nginx start
else
    service nginx restart
fi;

sudo nginx -t
