#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains

sudo apt-get update -y
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World' | sudo tee /var/www/html/index.html


echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

sudo sed -i '/^server {/a error_page 404 /404.html;' /etc/nginx/sites-available/default

sudo service nginx restart

sudo nginx -t
