#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80 When querying
#As an answer file, write a Bash script that configures
#You can’t use systemctl for restarting nginx

HEADER="add_header X-Served-By $(hostname) always;"
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

sudo sed -i "/server {/ a $HEADER" /etc/nginx/sites-available/default

sudo ufw allow 'Nginx HTTP'
sudo service nginx start
