#!/usr/bin/env bash
# Don't use systemctl ever in any ALX Server
# Write a Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user ubuntu.

ssh -i ~/.ssh/school ubuntu@107.23.102.134
