#!/usr/bin/env bash
# modify web stack debuging0 previous task to change nginx default port to 80
cp -r /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep nginx) | head -n 1)"
