#!/usr/bin/env bash
# make above code short
sudo apt update -y & apt upgrade -y & apt install nginx -y & apt install net-tools -y
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart
